### ISSUE TITLE
B1 Correction on MTsat

### ISSUE THREAD

**Issue by nicksisco1932** [qMRLab/documentation#8]
I was hoping to add a B1 map to correct for flip angle imperfection and was looking through the source code for MTSAT_exec. Using MATLAB's debug feature and placing it at line 44, I noticed that Alpha_B1 is just a set number even if I supply a B1 map. 

I can fix it on my own, but I am more/less just pointing out something. Unless I'm missing something, I don't think that it is working as intended. 

Best,
Nick

**Comment by nicksisco1932** [comment]
Nevermind. I see it now.

**Comment by mathieuboudreau** [comment]
Thanks @nicksisco1932 !

Just for posperity, I think what you saw was that we multiply Alpha_B1 with the B1 map on this line: 

https://github.com/qMRLab/qMRLab/blob/ccea5bd6454b1ca464bdd4686dcfbb5b368d7b74/src/Models_Functions/MTSATfun/MTSAT_exec.m#L41

**Comment by nicksisco1932** [comment]
Yeah, you're right about my mistake. I got ahead of myself! I opened the paper that was mentioned and there was a big fat formula I missed. Sorry about that.
